blank_issues_enabled: false
contact_links:
  - name: IMS Home Page
    url: https://ims.esapps.in/about/
    about: Online Stock and Inventory Management Software
  - name: IMS Knowledgebase
    url: https://github.com/Erratums/ims-support/discussions
    about: Please ask and answer questions here
