blank_issues_enabled: false
contact_links:
  - name: IMS Home Page
    url: https://ims.esapps.in/about/
    about: Online Stock and Inventory Management Software
  - name: IMS Web App
    url: https://ims.esapps.in
    about: Please ask and answer questions here
